### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by cary-rowen**
* Added Simplified Chinese translation.
* Fixed missing translatable string.
* Corrected pythonScript path.

### CODE REVIEW

**Comment by cary-rowen** [comment]
Hi @OSadovy 

Are you following this project and do you plan to merge translation requests?

Thanks

**Comment by OSadovy** [comment]
Hi @cary-rowen !
Thanks for your contribution! Sorry, I missed the notification somehow.

**Comment by cary-rowen** [comment]
Hi @OSadovy 

Would you consider updating the dependencies so that the add-on is compatible with NVDA2024.1

Thanks

**Comment by OSadovy** [comment]
@cary-rowen 
Yeah, I'll look into that. Although most probably the new version of extension will be not backward compatible with NVDA versions pre python 3.11, due to binary dependencies.

**Pull request merged**
